name: Reset Commit History

on:
  workflow_dispatch:
    inputs:
      event:
        type: choice
        description: 'on or off'
        options:
          - turn-on


jobs:
  reset_history:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"

    - name: Filter and squash sre-croquis commits
      run: |
        # sre-croquis의 커밋 해시 가져오기
        SRE_COMMITS=$(git log --author="leelee3264" --pretty=format:"%h")
        
        # 기본적으로 squash로 합치기
        git reset --soft $(echo $SRE_COMMITS | tail -n 1)  # 가장 오래된 커밋 해시로 리셋
        git commit --amend -m "Squash sre-croquis commits"
        
    - name: Push changes
      run: |
        git push origin main --force  # 강제 푸시
