name: Reset Commit History

on:
  workflow_dispatch:
    inputs:
      event:
        type: choice
        description: 'on or off'
        options:
          - turn-on


jobs:
  squash_commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.SRE_ACCOUNT_TOKEN }}'

      - name: Remove commits by sre-croquis
        run: |
          git checkout main
          git fetch origin
          git rebase -i --onto $(git rev-list --reverse --all --author="leelee3264" | tail -n 1) HEAD~1
          git push -f origin main
