name: Reset Commit History

on:
  workflow_dispatch:
    inputs:
      event:
        type: choice
        description: 'on or off'
        options:
          - turn-on


jobs:
  squash_commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.SRE_ACCOUNT_TOKEN }}'

      - name: Remove commits by sre-croquis
        run: |
          git filter-branch --commit-filter '
            if [ "$GIT_AUTHOR_NAME" = "leelee3264" ];
            then
              skip_commit "$@";
            else
              git commit-tree "$@";
            fi' HEAD
          git push -f origin main
