name: Reset Commit History

on:
  workflow_dispatch:
    inputs:
      event:
        type: choice
        description: 'on or off'
        options:
          - turn-on


jobs:
  compress_commits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"

    - name: Find sre-croquis commits
      id: sre_commits
      run: |
        # sre-croquis의 커밋 해시 목록을 파일로 저장
        git log --author="leelee3264" --reverse --pretty=format:"%h" > sre_commits.txt

    - name: Rebase sre-croquis commits
      run: |
        # 가장 오래된 커밋 해시를 사용해 리베이스 시작
        BASE_COMMIT=$(head -n 1 sre_commits.txt)
        if [ -n "$BASE_COMMIT" ]; then
          git rebase -i $BASE_COMMIT^
        fi

        # 리베이스 과정에서 자동으로 squash 설정
        sed -i 's/pick/squash/g' .git/rebase-merge/git-rebase-todo
        git rebase --continue

    - name: Push changes
      run: |
        git push origin main --force
